image: golang:latest

cache:
  paths:
    - vendor/

stages:
  - prepare
  - test
  - build
  - release

install-dependencies:
  stage: prepare
  script:
    - go get -v

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    # disabled go vet, for now: https://github.com/golang/go/issues/45604
    # - go vet $(go list ./... | grep -v /vendor/)
    # i do not have any tests to run
    # - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - ./psychedelic_flamingo-linux_amd64

release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                  # Run this job when a tag is created manually
  script:
    - echo "Running the release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: '$CI_COMMIT_TAG'
    description: 'Release created using the release-cli.'
    assets:
      links:
        - name: "psychedelic_flamingo-linux_amd64"
          url: https://gitlab.com/$CI_PROJECT_PATH/-/jobs/$CI_PIPELINE_ID/artifacts/file/psychedelic_flamingo-linux_amd64
          link_type: package