version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - binary: "mi2-collector"

dockers:
  - image_templates:
      - "ghcr.io/surdaft/ble-mi2-statsd-collector:latest"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
